--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  data:
    redis:
      host: localhost
      port: 6379
      password:

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "db-dev"
  data:
    redis:
      host: keytris-redis
      port: 8380
      username: ${REDIS_USERNAME_DEV}
      password: ${REDIS_PASSWORD_DEV}

--- # prod 설정
spring:
  config:
    activate:
      on-profile: "db-prod"
  data:
    redis:
      host: keytris-redis
      port: 8379
      username: ${REDIS_USERNAME_PROD}
      password: ${REDIS_PASSWORD_PROD}