spring:
  config:
    activate:
      on-profile: "data-local"
data:
  url: "http://localhost:8766/api/data"

---
spring:
  config:
    activate:
      on-profile: "data-dev"
data:
  url: "http://j9a401b.p.ssafy.io:8766/data"

---
spring:
  config:
    activate:
      on-profile: "data-prod"
data:
  url: "http://j9a401b.p.ssafy.io:8765/api/data"