package com.ssafy.confidentIs.keytris.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    NOT_FOUND(404,"CM01-ERR-404","PAGE NOT FOUND"),
    INTERNAL_SERVER_ERROR(500,"CMO2-ERR-500","INTERNAL SERVER ERROR"),
    BAD_REQUEST(400, "CM03-ERR-400", "BAD REQUEST"),
    INVALID_INPUT_VALUE(400,"CMO4-ERR-400","INVALID INPUT VALUE"),

    INVALID_WORD(400,"GAO1-ERR-400","INVALID WORD"),
    PLAYER_NOT_FOUND(404, "GA02-ERR-404", "PLAYER NOT FOUND"),
    ROOM_NOT_FOUND(404, "GA03-ERR-404", "ROOM NOT FOUND"),
    INACCESSIBLE_GAME(403, "GA04-ERR-403", "INACCESSIBLE GAME"),

    SOCKET_INVALID_WORD(400,"SOO1-ERR-400","INVALID WORD"),
    SOCKET_PLAYER_NOT_FOUND(404, "SO02-ERR-404", "PLAYER NOT FOUND"),
    SOCKET_ROOM_NOT_FOUND(404, "SO03-ERR-404", "ROOM NOT FOUND"),
    SOCKET_INVALID_START(403, "SO04-ERR-400", "INVALID START"),
    SOCKET_NOT_AUTHORIZED(403, "SO05-ERR-403", "NOT AUTHORIZED")
    ;

    private int status;
    private String errorCode;
    private String message;

}
